export const LOAD_MAIN_START = 'LOAD_MAIN_START'
export const LOAD_MAIN_SUCCESS = 'LOAD_MAIN_SUCCESS'
export const LOAD_MAIN_FAILURE = 'LOAD_MAIN_FAILURE'

export const LOAD_MORE_START = 'LOAD_MORE_START'
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE'

export const LOAD_DETAIL_START = 'LOAD_DETAIL_START'
export const LOAD_DETAIL_SUCCESS = 'LOAD_DETAIL_SUCCESS'
export const LOAD_DETAIL_FAILURE = 'LOAD_DETAIL_FAILURE'